### PR TITLE
fix MATCHED VARS issues

### LINKED ISSUE #174: MATCHED_VAR_NAME macro expansion contains value as well.
## Description
MATCHED_VAR_NAME macro expansion contains value as well.
MATCHED_VAR_NAME  should only contain the var name and should not have any reference to value.
```
transaction.go
// matchVariable Creates the MATCHED_ variables required by chains and macro expansion
// MATCHED_VARS, MATCHED_VAR, MATCHED_VAR_NAME, MATCHED_VARS_NAMES
func (tx *Transaction) matchVariable(match MatchData) {
....
	// TODO this is a temporary fix, the match should be VARIABLE:key
	varname += fmt.Sprintf(":%s", match.Value)
...
}
```	
### Steps to reproduce
`SecRule ARGS:param1 "test" "id:1,phase:1,log,msg:'test rule',logdata:'Matched %{MATCHED_VAR_NAME}'"`

`tx.ProcessURI("/script.pl?param1=test", "POST", "HTTP/1.1")`

### Expected result
match_rule.Data:: Matched ARGS:param1

### Actual result
match_rule.Data::  Matched ARGS:param1:test

### PR DESCRIPTION
**Pull request by jptosso**
#174:
The data structure for ARGS_NAMES and ARGS_GET_NAMES used to be:
```json
{
    "": ["name 1", "name 2", "name 3"]
}
```
Now it has become:
```json
{
  "name 1": "name 1",
  "name 2": "name 2",
  "name 3": "name 3",
}
```

There is some redundancy but with the current design it solves the problem for CRS rule 920271 that expects the key name from ARGS_NAMES using MATCHED_VAR_NAME. In the old design MATCHED_VAR_NAME would return just ARGS_NAMES because the arg name was a value, not a key. In coraza v3 there should be a new design for this.

#173:

I've just added the key to MATCHED_VARS:
```go
matchedVars.Add(variableName.String(), match.Value)
```

Tests were added for both cases.

### CODE REVIEW

**Comment by jptosso** [comment]
BTW, This is a milestone for v2.0.0-rc.3

File: transaction.go [hunk 1]
```diff
@@ -266,12 +266,12 @@ func (tx *Transaction) matchVariable(match MatchData) {
 	// Array of keys
 	matchedVarsNames := tx.GetCollection(variables.MatchedVarsNames)
 
-	matchedVars.Add("", match.Value)
+	matchedVars.Add(match.Key, match.Value)
```
Comment (bxlxx) [inline transaction.go:269]: I think ```varName.String()``` should be used instead of ```match.Key``` to prevent confusion of the same key in different ```RuleVariable```

File: transaction.go [hunk 2]
```diff
@@ -266,12 +266,12 @@ func (tx *Transaction) matchVariable(match MatchData) {
...
 	matchedVar.SetIndex("", 0, match.Value)
 	// fmt.Printf("%s: %s\n", match.VariableName, match.Value)
 
-	matchedVarsNames.Add("", varName)
-	matchedVarName.SetIndex("", 0, varName)
+	matchedVarsNames.Add("", varName.String())
```
Comment (bxlxx) [inline transaction.go:273]: How about using the ```matchedVarNames.Add(varName.String(), varName.String())```

**Review by bxlxx — COMMENTED** [review]
LGTM

**Review by bxlxx — APPROVED** [review]
