### PR TITLE
fix: streamed responses

### LINKED ISSUE #1120: Streamed Responses aren't Coming Through Until Finalized
## Description

NextJs uses streams to send data asynchronously to web clients.

When a NextJs application is deployed behind a Coraza WAF extended Caddy server, streamed responses are hindered by the SecRuleEngine.  If there for example is a spinner that NextJs wants the browser to render until data is fetched in the background, it will not show up and the browser will be dead silent until the data is coming through.

I've tried to disable everything body access, I've tried to write a rule that allows any response. Nothing helps except disabling `SecRuleEngine` completely. 

### Steps to reproduce

We've setup an example repo that reproduces the problem. The project consists of a small NextJs application behind a Caddy server. The issue is appearing by default in this repo. 

https://github.com/svenakela/coraza-streaming-issue

Disable `SecRuleEngine` and the app works as expected.

### Expected result

In this example project the bottom text should change to _Loading..._ until data is sent by the app server.

### Actual result

No textual change at all. The bottom text only change when the response is ready in the app server.

### PR DESCRIPTION
**Pull request by daum3ns**
This pull request fixes #1120 by preventing Coraza from buffering responses when `SecResponseBodyAccess off` is enabled.

* Added streaming_test.go for tests regarding streamed responses. 
* Introduced a new flag `allowFlushing` in the interceptor.go 

- [x] My code includes positive and negative tests.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v3sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).
- [x] My code is properly linted and passes pre-commit tests.

Thanks for your contribution :heart:

### CODE REVIEW

**Comment by jcchavezs** [comment]
GREAT WORK! Any chance we get a test in e2e? https://github.com/corazawaf/coraza/blob/main/http/e2e/e2e.go

**Comment by daum3ns** [comment]
are the e2e tests intended to be run manually? at least it looks like it expects something running on localhost 8080 and 8081?

**Comment by daum3ns** [comment]
i think the current e2e setup doesn't allow to easily do that...

**Comment by daum3ns** [comment]
I have added the basis for the e2e test, however at the moment there is no verification on client side that the response is streamed. in other words the test also succeeds if we put it in the Run() method, (which shouldn't because the body is buffered).. 

Also do you think its better to have an own set of directives, or should I integrate it in the existing directives using this Rule:
`SecRule RESPONSE_CONTENT_TYPE "text/event-stream" "id:1001,phase:3,log,allow,ctl:responseBodyAccess=Off"`
Or even both maybe its worth having this rule tested too?

**Comment by daum3ns** [comment]
okay I think this should be fine for an e2e scenario.. I figured out that we can easily do it in the main Run because of the MimeType settings. Response body access is on, but the mime type is not defined (i.e. tx.IsProcessable == false) to be inspected so the body gets streamed correctly. I have additionally added such a setup in the streaming_test.go. 
The only reason to maybe keep a separate runner would be if we, for some reason, want an isolated streaming test setup with different directives ... but at the moment I don't think its needed.


however, when I was playing around with the directives, I fount out that removing the `SecResponseBodyMimeType` directive entirely, it causes a panic in the test "Denied request with a malicious response header" 

```
 [5/9] Running test: Denied request with a malicious response header
2025/12/12 15:56:33 http: panic serving 127.0.0.1:57320: http: wrote more than the declared Content-Length
goroutine 5 [running]:
net/http.(*conn).serve.func1()
	/usr/lib/go/src/net/http/server.go:1943 +0xd3
panic({0xba8960?, 0xc0004125c0?})
	/usr/lib/go/src/runtime/panic.go:783 +0x132
github.com/mccutchen/go-httpbin/v2/httpbin.mustMarshalJSON({0x7f50d2f5c440?, 0xc000438360?}, {0xc8fb20?, 0xc000406a80?})
	/home/doi/go/pkg/mod/github.com/mccutchen/go-httpbin/v2@v2.18.3/httpbin/helpers.go:120 +0xbc
github.com/mccutchen/go-httpbin/v2/httpbin.(*HTTPBin).ResponseHeaders(0xc0002ce1e0, {0xe3c1f0, 0xc000438360}, 0xc000404200?)
	/home/doi/go/pkg/mod/github.com/mccutchen/go-httpbin/v2@v2.18.3/httpbin/handlers.go:374 +0x2f5
net/http.HandlerFunc.ServeHTTP(0xc00015c180?, {0xe3c1f0?, 0xc000438360?}, 0xc000404200?)
	/usr/lib/go/src/net/http/server.go:2322 +0x29
net/http.(*ServeMux).ServeHTTP(0xe3c1f0?, {0xe3c1f0, 0xc000438360}, 0xc000436280)
	/usr/lib/go/src/net/http/server.go:2861 +0x1c7
github.com/mccutchen/go-httpbin/v2/httpbin.(*HTTPBin).Handler.limitRequestSize.func1({0xe3c1f0?, 0xc000438360?}, 0xc000436280?)
	/home/doi/go/pkg/mod/github.com/mccutchen/go-httpbin/v2@v2.18.3/httpbin/middleware.go:42 +0xa5
net/http.HandlerFunc.ServeHTTP(0xc000406360?, {0xe3c1f0?, 0xc000438360?}, 0xcede56?)
	/usr/lib/go/src/net/http/server.go:2322 +0x29
github.com/mccutchen/go-httpbin/v2/httpbin.(*HTTPBin).Handler.preflight.func2({0xe3c1f0, 0xc000438360}, 0xc000436280)
	/home/doi/go/pkg/mod/github.com/mccutchen/go-httpbin/v2@v2.18.3/httpbin/middleware.go:33 +0x1eb
net/http.HandlerFunc.ServeHTTP(0x7f50d59c1c00?, {0xe3c1f0?, 0xc000438360?}, 0x0?)
	/usr/lib/go/src/net/http/server.go:2322 +0x29
github.com/mccutchen/go-httpbin/v2/httpbin.(*HTTPBin).Handler.autohead.func3({0xe3c1f0?, 0xc000438360?}, 0xc0004041c0?)
	/home/doi/go/pkg/mod/github.com/mccutchen/go-httpbin/v2@v2.18.3/httpbin/middleware.go:62 +0xe9
net/http.HandlerFunc.ServeHTTP(0x8?, {0xe3c1f0?, 0xc000438360?}, 0xc000404170?)
	/usr/lib/go/src/net/http/server.go:2322 +0x29
github.com/mccutchen/go-httpbin/v2/httpbin.(*HTTPBin).ServeHTTP(0xe3c0a0?, {0xe3c1f0?, 0xc000438360?}, 0xe4ae40?)
	/home/doi/go/pkg/mod/github.com/mccutchen/go-httpbin/v2@v2.18.3/httpbin/httpbin.go:131 +0x2c
github.com/corazawaf/coraza/v3/testing/e2e_test.TestE2e.WrapHandler.func3({0xe3c0a0, 0xc0004140f0}, 0xc000436280)
	/home/doi/01_workspace/core-waap/coraza/http/middleware.go:148 +0x122
net/http.HandlerFunc.ServeHTTP(0xc00015c540?, {0xe3c0a0?, 0xc0004140f0?}, 0x7b1b56?)
	/usr/lib/go/src/net/http/server.go:2322 +0x29
net/http.(*ServeMux).ServeHTTP(0x47f199?, {0xe3c0a0, 0xc0004140f0}, 0xc000436280)
	/usr/lib/go/src/net/http/server.go:2861 +0x1c7
net/http.serverHandler.ServeHTTP({0xc0003a60c0?}, {0xe3c0a0?, 0xc0004140f0?}, 0x1?)
	/usr/lib/go/src/net/http/server.go:3340 +0x8e
net/http.(*conn).serve(0xc0000b6000, {0xe3e348, 0xc000382120})
	/usr/lib/go/src/net/http/server.go:2109 +0x665
created by net/http.(*Server).Serve in goroutine 21
	/usr/lib/go/src/net/http/server.go:3493 +0x485

```

this happens in the main branch as well, so it's not introduced by this PR.. But I don't know, do you guys think that it is a problem?

**Comment by jcchavezs** [comment]
Amazing work! I am inclined to merge it. Any thoughts @M4tteoP ?

**Comment by jcchavezs** [comment]
I took the freedom to cherry-pick some of the great improvements in here that are not tied to the streaming support into another PR so we can review this easier https://github.com/corazawaf/coraza/pull/1459

**Comment by jcchavezs** [comment]
Testing the e2e in 
- coraza-proxy-wasm https://github.com/corazawaf/coraza-proxy-wasm/pull/312
- coraza-caddy https://github.com/corazawaf/coraza-caddy/pull/253 (I suspect it will fail)

@fionera wanna test it in coraza-spoa?

**Comment by jcchavezs** [comment]
Apparently it works as expected in envoy https://github.com/corazawaf/coraza-proxy-wasm/actions/runs/20431263460/job/58705278664?pr=312#step:9:438

**Comment by jcchavezs** [comment]
It failed as expected in caddy :) https://github.com/corazawaf/coraza-caddy/actions/runs/20432299095/job/58705536937?pr=253#step:7:206

**Comment by jcchavezs** [comment]
Looks like it works, thanks! but I'd like a second review from @M4tteoP

File: http/e2e/e2e.go [hunk 1]
```diff
@@ -144,6 +149,91 @@ func expectEmptyBody() bodyExpectation {
...
+	ct := strings.ToLower(resp.Header.Get("Content-Type"))
+	if !strings.Contains(ct, "text/event-stream") {
+		return fmt.Errorf("expected Content-Type text/event-stream, got %q", resp.Header.Get("Content-Type"))
+	}
+	if cl := resp.Header.Get("Content-Length"); cl != "" {
+		return fmt.Errorf("expected no Content-Length for streaming, got %q", cl)
+	}
+
+	// Sanitize deadlines
+	if totalDeadline <= 0 {
```
Comment (jcchavezs) [inline http/e2e/e2e.go]: I'd rather force the totalDeadline to be passed.

File: http/e2e/e2e.go [hunk 2]
```diff
@@ -144,6 +149,91 @@ func expectEmptyBody() bodyExpectation {
...
+		totalDeadline = 30 * time.Second
+	}
+	if firstChunkDeadline < 0 {
```
Comment (jcchavezs) [inline http/e2e/e2e.go:184]: in which case would this be <0?

File: http/e2e/e2e.go [hunk 3]
```diff
@@ -144,6 +149,91 @@ func expectEmptyBody() bodyExpectation {
...
+			inEvent = true
+			if !gotFirst {
+				gotFirst = true
+				firstAt = time.Now()
+			}
+		}
+		if inEvent && strings.HasPrefix(s, "data:") {
+			events++
+			inEvent = false
+			if events >= expectedEvents {
```
Comment (jcchavezs) [inline http/e2e/e2e.go]: I'd sanitize that expectedEvents > 0 at the beginning of the function

**Comment by svenakela** [comment]
Great work! :tada: 
When can I expect this code to be in a release?
