### PR TITLE
fix: parse multiple cookies with spaces

### LINKED ISSUE #942: REQUEST_COOKIES keys can contain a whitespace
Hello,

## Description

In case of a multiple-cookie header, a web application compliant with RFC 6265 will add a whitespace after the ';' character :
https://www.ietf.org/rfc/rfc6265.txt section 3.1
>    As shown in the next example, the server can store multiple cookies
>    at the user agent.  For example, the server can store a session
>    identifier as well as the user's preferred language by returning two
>    Set-Cookie header fields.  Notice that the server uses the Secure and
>    HttpOnly attributes to provide additional security protections for
>    the more sensitive session identifier (see Section 4.1.2.)
> 
>    == Server -> User Agent ==
> 
>    Set-Cookie: SID=31d4d96e407aad42; Path=/; Secure; HttpOnly
>    Set-Cookie: lang=en-US; Path=/; Domain=example.com
> 
>    == User Agent -> Server ==
> 
>    Cookie: SID=31d4d96e407aad42; lang=en-US

Unfortunately, coraza does not trim the whitespace when creating the REQUEST_COOKIES variable, which makes one unable to ruleRemoveTargetByXX on the cookie for example.

### Steps to reproduce

I tried to share the playground but I can't, here is the directives to put (2 cookies, 933150 rule but only matching "rtrim" php function, then try to removetarget with both cookies) :
```
SecAction "id:1002,phase:1,pass,nolog,ctl:ruleRemoveTargetByTag=language-php;REQUEST_COOKIES:_Cookie_A"
SecAction "id:1003,phase:1,pass,nolog,ctl:ruleRemoveTargetByTag=language-php;REQUEST_COOKIES:_Cookie_B"

SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|ARGS_NAMES|ARGS|XML:/* "@pm rtrim" \
    "id:9331500,\
    phase:2,\
    block,\
    capture,\
    t:none,\
    msg:'PHP Injection Attack: High-Risk PHP Function Name Found',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'language-php',\
    ver:'OWASP_CRS/4.0.0-rc2',\
    severity:'CRITICAL',\
    setvar:'tx.php_injection_score=+%{tx.critical_anomaly_score}',\
    setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'"
```

And here is the HTTP request
```
GET / HTTP/2
Host: tstcookie
Cookie: _Cookie_A=RTRIM; _Cookie_B=RTRIM
```
Run it as-is and you'll see that the rule matches, then remove the whitespace after ';' and re-run to see no rule matched (it actually gets removed by rule 1003).

### Expected result

Whitespace removed after ';' when creating the REQUEST_COOKIE variable

Regards,

### PR DESCRIPTION
**Pull request by fzipi**
> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Make sure that you've checked the boxes below before you submit PR:**

- [x] My code includes positive and negative tests.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v3sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).
- [x] My code is properly linted and passes pre-commit tests.

Thanks for your contribution :heart:

Fixes #942.

### CODE REVIEW

**Review by M4tteoP — APPROVED** [review]
Looks good to me. I would also remove [ParseQueryWithoutUnescape](https://github.com/corazawaf/coraza/blob/fc1596e54f7dab4e9bebeafda57911e7d58bac57/internal/url/url.go#L17). It has been recently added in order to reuse ParseQuery with cookies, but considering the new specific function `ParseCookies` I think it is not needed anymore.

File: internal/corazawaf/transaction.go [hunk 1]
```diff
@@ -320,9 +321,21 @@ func (tx *Transaction) AddRequestHeader(key string, value string) {
...
+		//   The user agent sends stored cookies to the origin server in the
+		//   Cookie header.  If the server conforms to the requirements in
+		//   Section 4.1 (and the user agent conforms to the requirements in
+		//   Section 5), the user agent will send a Cookie header that conforms to
+		//   the following grammar:
+		//
+		//   cookie-header = "Cookie:" OWS cookie-string OWS
+		//   cookie-string = cookie-pair *( ";" SP cookie-pair )
+		//
+		// There is no URL Decode performed no the cookies
```
Comment (M4tteoP) [inline internal/corazawaf/transaction.go:337]:
```suggestion
		// There is no URL Decode performed on the cookies
```

**Comment by fzipi** [comment]
Removed the unused function/method.
