### PR TITLE
fix: SecRuleUpdateActionById should replace disruptive actions

### LINKED ISSUE #1414: SecRuleUpdateActionById does not actually replace actions
## Description

When using `SecRuleUpdateActionById`, the new actions are simply appended to the list of existing actions for the rule, which prevents it from being used to disable specific rules.

### Steps to reproduce

```
SecRule ARGS:id "@eq 0" "id:1, phase:1,deny,status:403,msg:'Invalid id',log,auditlog"
SecRuleUpdateActionById 1 "log,pass"
```

The first rule uses a `deny` action to block a request if the `id` parameter is equals to 0.
But there's a `SecRuleUpdateActionById` to change the action to `pass` which should allow the request.

### Expected result

Request blocked.

I've tested those rules with modsecurity, and the behaviour is the expected one: the request is allowed.

### Actual result

The request is not blocked:

```
~/git/coraza/examples/http-server (main ✘)✹ ᐅ go run main.go
2025/08/28 14:47:44 [DEBUG] Parsing directive line="SecRule ARGS:id \"@eq 0\" \"id:1, phase:1,deny,status:403,msg:'Invalid id',log,auditlog\""
2025/08/28 14:47:44 [DEBUG] Parsing directive line="SecRuleUpdateActionById 1 \"log,pass\""
Server is running. Listening port: 8090
2025/08/28 14:47:56 [DEBUG] Transaction started tx_id="QyVhEtdOAzffqKwkdpM"
2025/08/28 14:47:56 [DEBUG] Evaluating phase tx_id="QyVhEtdOAzffqKwkdpM" phase=1
2025/08/28 14:47:56 [DEBUG] Evaluating rule tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1
2025/08/28 14:47:56 [DEBUG] Expanding arguments for rule tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1 variable="ARGS"
2025/08/28 14:47:56 [DEBUG] Matching rule tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1 variable_name="ARGS" key="id"
2025/08/28 14:47:56 [DEBUG] Evaluating action tx_id="QyVhEtdOAzffqKwkdpM" action="log"
2025/08/28 14:47:56 [DEBUG] Evaluating action tx_id="QyVhEtdOAzffqKwkdpM" action="auditlog"
2025/08/28 14:47:56 [DEBUG] Evaluating action tx_id="QyVhEtdOAzffqKwkdpM" action="log"
2025/08/28 14:47:56 [DEBUG] Evaluating operator: MATCH tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1 variable="ARGS" operator_function="@eq" operator_data="0" arg="0"
2025/08/28 14:47:56 [DEBUG] Executing disruptive action for rule tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1 action="deny"
2025/08/28 14:47:56 [DEBUG] Executing disruptive action for rule tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1 action="pass"
2025/08/28 14:47:56 [DEBUG] Rule matched tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1
[logError][emergency] [client "[::1]"] Coraza: Access denied (phase 1). Invalid id [file "default.conf"] [line "4"] [id "1"] [rev ""] [msg "Invalid id"] [data ""] [severity "emergency"] [ver ""] [maturity "0"] [accuracy "0"] [hostname ""] [uri "/?id=0"] [unique_id "QyVhEtdOAzffqKwkdpM"]
2025/08/28 14:47:56 [DEBUG] Finished rule evaluation tx_id="QyVhEtdOAzffqKwkdpM" rule_id=1
2025/08/28 14:47:56 [DEBUG] Finished phase tx_id="QyVhEtdOAzffqKwkdpM" phase=1
2025/08/28 14:47:56 [DEBUG] Evaluating phase tx_id="QyVhEtdOAzffqKwkdpM" phase=5
2025/08/28 14:47:56 [DEBUG] Finished phase tx_id="QyVhEtdOAzffqKwkdpM" phase=5
2025/08/28 14:47:56 [DEBUG] Transaction marked for audit logging tx_id="QyVhEtdOAzffqKwkdpM"
2025/08/28 14:47:56 [DEBUG] Transaction finished tx_id="QyVhEtdOAzffqKwkdpM" is_interrupted=true status=403 rule_id=1
```

As we can see in the logs, both `deny` and `pass` actions are specified for the rule (and `log` twice), and because `pass` is a noop, the interruption set by `deny` is returned, which blocks the request.

### PR DESCRIPTION
**Pull request by fzipi**
## what

- fixed SecRuleUpdateActionById implementation
  - internal/corazawaf/rule.go: Added ClearActionsOfType() method to remove actions by type
  - internal/seclang/directives.go:
    - modified updateActionBySingleID() to parse actions first and only clear disruptive actions if the update contains disruptive actions
    - this preserves disruptive actions when only non-disruptive actions are updated

- fixed Test Validation Logic:
  - testing/engine.go: fixed OutputInterruptionErrors() to properly validate ALL interruption cases:
    - before: Only checked details when both expected AND actual interruption existed
    - after: Also checks for unexpected interruptions and missing expected interruptions

- added comprehensive tests:
  - testing/engine/directives_updateactions.go: Added 3 test scenarios:
    a. Original tests with explicit "no interruption" comments
    b. New: Updating with non-disruptive actions preserves disruptive action
    c. New: Exact scenario from GitHub issue #1414
  - enhanced coverage from testing/engine.go

### Test Results

All tests now properly validate:
- ✅ Disruptive actions are replaced when update contains disruptive actions
- ✅ Disruptive actions are preserved when update contains only non-disruptive actions
- ✅ No interruptions occur when deny is replaced with pass (issue #1414)
- ✅ Interruptions with correct action type occur when expected

## why

- fix SecRuleUpdateActionById implementation
- fixes #1414

### CODE REVIEW

**Comment by fzipi** [comment]
@copilot open a new pull request to apply changes based on the comments in [this thread](https://github.com/corazawaf/coraza/pull/1471#pullrequestreview-3658154243)

**Comment by fzipi** [comment]
@copilot open a new pull request to apply changes based on the comments in [this thread](https://github.com/corazawaf/coraza/pull/1471#pullrequestreview-3658154243)

File: internal/seclang/directives.go [hunk 1]
```diff
@@ -1152,18 +1164,34 @@ func directiveSecRuleUpdateActionByID(options *DirectiveOptions) error {
 				return fmt.Errorf("invalid range: %s", idOrRange)
 			}
 
+			// Parse actions once to check if any are disruptive
+			trimmedActions := strings.Trim(actions, "\"")
```
Comment (jcchavezs) [inline internal/seclang/directives.go:1171]: Curious why we need the trim here. Could you please add a comment?

File: internal/seclang/directives.go [hunk 2]
```diff
@@ -1152,18 +1164,34 @@ func directiveSecRuleUpdateActionByID(options *DirectiveOptions) error {
...
+			if err != nil {
+				return err
+			}
+
+			// Check if any of the new actions are disruptive
+			hasDisruptiveAction := hasDisruptiveActions(parsedActions)
+
 			for _, rule := range options.WAF.Rules.GetRules() {
-				if rule.ID_ < start && rule.ID_ > end {
+				if rule.ID_ < start || rule.ID_ > end {
```
Comment (jcchavezs) [inline internal/seclang/directives.go]: LOL, this looks like a weird bug!

File: testing/engine_test.go [hunk 3]
```diff
@@ -95,6 +96,673 @@ func TestResponse(t *testing.T) {
 	*/
 }
 
+func TestOutputInterruptionErrors_NoInterruptionExpectedButGot(t *testing.T) {
```
Comment (jcchavezs) [inline testing/engine_test.go]: This is getting too long, probably move to another file?

File: internal/corazawaf/rule.go [hunk 4]
```diff
@@ -467,6 +467,26 @@ func (r *Rule) AddAction(name string, action plugintypes.Action) error {
...
+//
+// This helper is typically used by rule parsers or directives that need to override
+// previously configured actions for a rule (for example, to clear all disruptive or
+// logging actions before adding new ones) without modifying the rest of the rule
+// definition.
+//
+// The actionType argument identifies the logical category of actions to remove, as
+// reported by Action.Type() (such as disruptive, non-disruptive, or logging). Any
+// action whose Type() matches actionType is filtered out from r.actions.
+func (r *Rule) ClearActionsOfType(actionType plugintypes.ActionType) {
```
Comment (jcchavezs) [inline internal/corazawaf/rule.go]: this is clearly only be used for disruptive actions so I'd rather change into `ClearDisruptiveActions` instead. If at some point we need to extend it for other type we can generalise it.

File: internal/seclang/directives.go (hunk 1 above)
Comment (jcchavezs) [reply internal/seclang/directives.go:1171]: I know you didn't add this but I was hoping you could make sense of it.

**Comment by jcchavezs** [comment]
@M4tteoP please review this.

File: testing/engine_test.go (hunk 3 above)
Comment (fzipi) [reply testing/engine_test.go]: Splitted heuristically where it looked reasonable.

File: internal/seclang/directives.go (hunk 1 above)
Comment (fzipi) [reply internal/seclang/directives.go:1171]: Added comment.

File: internal/seclang/directives.go (hunk 2 above)
Comment (fzipi) [reply internal/seclang/directives.go]: It does, right? This couldn't possible match IMHO.

**Comment by fzipi** [comment]
@M4tteoP Can you review this one?

File: internal/seclang/directives.go
Comment (M4tteoP) [inline internal/seclang/directives.go:1127]:
```suggestion
// ```
// The rule ID can be single IDs or ranges of IDs. The targets are separated by a pipe character.
```
Just like directiveSecRuleUpdateTargetByID, I see that we are supporting ID ranges, so I would document it

File: testing/engine/directives_updateactions.go [hunk 5]
```diff
@@ -52,13 +53,62 @@ var _ = profile.RegisterProfile(profile.Profile{
...
     SecRule ARGS "@contains value2" "phase:2,id:1014,block,deny"
 	SecRuleUpdateActionById 1014 "redirect:'https://www.example.com/',status:302"
+
+	# Test 2: Updating with non-disruptive actions should preserve disruptive action
+	SecRule ARGS:param "@contains trigger" "phase:1,id:2001,deny,status:403"
+	SecRuleUpdateActionById 2001 "log,auditlog"
+
+	# Test 3: Issue #1414 - exact scenario from the GitHub issue
+	SecRule ARGS:id "@eq 0" "id:3001, phase:1,deny,status:403,msg:'Invalid id',log,auditlog"
+	SecRuleUpdateActionById 3001 "log,pass"
```
Comment (M4tteoP) [inline testing/engine/directives_updateactions.go:130]:
```suggestion
	SecRuleUpdateActionById 3001 "log,pass"

	# Test 4: Range update - same scenario as test 3 but with two rules updated via range
	SecRule ARGS:id "@eq 0" "id:4001, phase:1,deny,status:403,msg:'Invalid id',log,auditlog"
	SecRule ARGS:id "@eq 0" "id:4002, phase:1,deny,status:403,msg:'Invalid id',log,auditlog"
	SecRuleUpdateActionById 4001-4002 "log,pass"
```
I would also test ranges

**Review by M4tteoP — DISMISSED** [review]

File: testing/engine/directives_updateactions.go [hunk 6]
```diff
@@ -110,5 +110,10 @@ var _ = profile.RegisterProfile(profile.Profile{
 	# Test 3: Issue #1414 - exact scenario from the GitHub issue
 	SecRule ARGS:id "@eq 0" "id:3001, phase:1,deny,status:403,msg:'Invalid id',log,auditlog"
 	SecRuleUpdateActionById 3001 "log,pass"
+
+	# Test 4: Range update - same scenario as test 3 but with two rules updated via range
```
Comment (M4tteoP) [inline testing/engine/directives_updateactions.go:132]: This would require also the real test that checks for 4001 and 4002, but we can do a follow up PR and have this one merged. Edit: I was wrong, it is already leading to some tests failing. We can take this in another PR.

**Comment by fzipi** [comment]
Fixed the range update bug: the `for _, rule := range` loop in `directiveSecRuleUpdateActionByID` was copying each `Rule` value, so modifications to disruptive actions were lost. Switched to index-based iteration (`for i := range rules` / `&rules[i]`) to modify rules in place.

Also added a test case (test 4) that exercises the range update path (`SecRuleUpdateActionById 4001-4002 "log,pass"`).

File: testing/engine/directives_updateactions.go (hunk 6 above)
Comment (fzipi) [reply testing/engine/directives_updateactions.go:132]: Fixed the range case.
